[package]
name = "chunks"
version = "0.1.0"
authors = ["Brent Hamilton <hamilton.bh9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.6"
log = "0.4.0"
env_logger = "0.8.3"
